### PR TITLE
French Support

### PR DESCRIPTION
**Pull request by iib0011**
image

### CODE REVIEW

**Review by cangzhang — CHANGES_REQUESTED** [review]
Please keep those .res files as they were, they have nothing to do with the  app.

**Comment by iib0011** [comment]
Ok. I fixed it

**Review by cangzhang — APPROVED** [review]

**Comment by cangzhang** [comment]
lgtm

**Comment by iib0011** [comment]
Okay

**Comment by iib0011** [comment]
It's done

**Review by cangzhang — APPROVED** [review]

**Review by cangzhang — APPROVED** [review]

**Pull request merged**
